config/routes.rb
Rails.application.routes.draw do
  get 'journeys/index'
  get 'journeys/show'
  get 'journeys/new'
  get 'journeys/create'
  get 'journeys/edit'
  get 'journeys/update'
  get 'journeys/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :journeys
  resources :cities, only:[:index, :show]
  resources :bookmarks, only:[:new, :create]

  get "/journeys/generate/new", to: "journeys#generate_new"
  post "/journeys/create/new", to: "journeys#create_new"

  get 'dashboard', to: 'pages#dashboard'
  get 'dashboard/current', to: "pages#dashboard_current"
  get 'dashboard/past', to: "pages#dashboard_past"

  get 'profile', to: 'pages#profile'

  resources :city_journeys, only:[:update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-dark rounded-pill alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-custom rounded-pill alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-white footer-container">
  <!-- Grid container -->
  <div class="p-4 pb-0">
    <h3><span class="footer-title">Find us on our socials</span></h3>
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="foot-link btn text-white btn-floating"
        style="background-color: #3b5998;"
        href="https://www.facebook.com/"
        target="_blank"
        role="button">
        <i class="footer-icon fab fa-facebook-f"></i>
      </a>

      <!-- Twitter -->
      <a
        class="foot-link btn text-white btn-floating"
        style="background-color: #55acee;"
        href="https://twitter.com/"
        target="_blank"
        role="button">
        <i class="footer-icon fab fa-twitter"></i>
      </a>

      <!-- Google -->
      <a
        class="foot-link btn text-white btn-floating"
        style="background-color: #dd4b39;"
        href="https://www.google.com/"
        target="_blank"
        role="button">
        <i class="footer-icon fab fa-google"></i>
      </a>

      <!-- Instagram -->
      <a
        class="foot-link btn text-white btn-floating"
        style="background-color: #ac2bac;"
        href="https://www.instagram.com/"
        target="_blank"
        role="button">
        <i class="footer-icon fab fa-instagram"></i>
      </a>

      <!-- Linkedin -->
      <a
        class="foot-link btn text-white btn-floating"
        style="background-color: #0082ca;"
        href="https://www.linkedin.com/"
        target="_blank"
        role="button">
        <i class="footer-icon fab fa-linkedin-in"></i>
      </a>

    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 copyright-box">
    © 2022 Copyright:
    <a class="text-white" href="#" target="_blank">TripsSelector.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "logo.png", style:"width: 10%;", class:"m-0", id: "image_space" %>
        <span class="navbar-text text-dark">
            Trips Selector
          </span>
      <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="right-side-buttons-nav collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "hdp-text nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "hdp-text nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", profile_path, class: "hdp-text nav-link text-dark", id: "profile-text" %>
          </li>
          <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
          <button style="border: none; background-color: transparent;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%# <%= cl_image_tag current_user.photo.key, height: 50, width: 50, crop: :thumb, class: "avatar dropdown-toggle", id: "navbarDropdown" %>
          <%= image_tag asset_path("ajavatar.jpg"), height: 50, width: 50, class: "avatar dropdown-toggle", id: "navbarDropdown" %>
          </button>
          <% else %>
          <%= image_tag asset_path("ajavatar.jpg"), height: 50, width: 50, class: "avatar dropdown-toggle", id: "navbarDropdown" %>
            <%# <%= image_tag "https://www.pngall.com/wp-content/uploads/5/Profile-Avatar-PNG-Free-Download.png", size: 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>