config/routes.rb
Rails.application.routes.draw do
  get 'journeys/index'
  get 'journeys/show'
  get 'journeys/new'
  get 'journeys/create'
  get 'journeys/edit'
  get 'journeys/update'
  get 'journeys/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :journeys
  resources :cities, only:[:index, :show]
  resources :bookmarks, only:[:new, :create]

  get "/journeys/generate/new", to: "journeys#generate_new"
  post "/journeys/create/new", to: "journeys#create_new"

  get 'dashboard', to: 'pages#dashboard'
  get 'dashboard/current', to: "pages#dashboard_current"
  get 'dashboard/past', to: "pages#dashboard_past"

  get 'profile', to: 'pages#profile'

  resources :city_journeys, only:[:update]
end

app/views/pages/dashboard.html.erb
<div class="db-banner">
  <h1 class="mb-5"> Dashboard </h1>
</div>

<div class="card-deck card-page-container">

  <ul class="nav nav-tabs mt-5">
    <li class="nav-item">
      <a class="nav-link" aria-current="page"> <%= link_to "Future journeys", dashboard_path, class: "nav-link active" %> </a>
    </li>
    <li class="nav-item">
      <a class="nav-link"> <%= link_to "Current journey", dashboard_current_path, class: "nav-link" %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link"> <%= link_to "Past journeys", dashboard_past_path, class: "nav-link" %></a>
    </li>
  </ul>

  <% if @journeys.empty? %>
    <h3 class='mt-5 mb-5'> You don't have any journeys with us. Start filling your dashboard by planning some trips! </h3>
  <% else %>
    <% if @journeys.last.start_date <= Date.today %>
      <h4 class='mt-5 mb-5'> It seems you don't have any future journeys. It's time to start planning ! </h4>
    <% else %>
      <div class="p-3 m-3 cards-container">
        <% @journeys.each do |journey| %>
          <% if journey.start_date > Date.today %>
            <div class="card shadow p-3 bg-white rounded-lg" id="dashboard-card" style="width: 18rem">
              <%= image_tag "#{journey.city_journeys.first.city.name}.jpg", :class => "dashboard-image" %>
              <div class="card-body text-center">
                <p><%= link_to "#{journey.name}", journey_path(journey) %></p>
                <p><%= journey.tag %></p>
                <div id="dates">
                  <p> From <%= journey.start_date.strftime("%a %d %B") %> to <%= journey.end_date.strftime("%a %d %B") %></p>
                </div>
                <button id="dashboard-button">
                  <%= link_to journey_path(journey), data: { "turbo-method": :delete }, id:"trash-icon" do %>
                    <i class="fa-solid fa-trash"></i>
                  <% end %>
                </button>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/dashboard_current.html.erb
<div class="db-banner">
  <h1 class="mb-5"> Dashboard </h1>
</div>

<div class="card-deck card-page-container">

  <ul class="nav nav-tabs mt-5">
    <li class="nav-item">
      <a class="nav-link" aria-current="page"> <%= link_to "Future journeys", dashboard_path, class: "nav-link" %> </a>
    </li>
    <li class="nav-item">
      <a class="nav-link"> <%= link_to "Current journey", dashboard_current_path, class: "nav-link active" %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link"> <%= link_to "Past journeys", dashboard_past_path, class: "nav-link" %></a>
    </li>
  </ul>

  <% if @journeys.empty? %>
    <h3 class='mt-5 mb-5'> You don't have any journeys with us. Start filling your dashboard by planning some trips! </h3>
  <% else %>
      <% if @current_journey.size == 0 %>
        <h4 class='mt-5 mb-5'> You are not currently travelling with us. What are you waiting for ? </h4>
      <% else %>
        <div class="p-3 m-3 cards-container">
            <% @journeys.each do |journey| %>
              <% if journey.start_date <= Date.today && journey.end_date >= Date.today %>
                <div class="card shadow p-3 bg-white rounded-lg" id="dashboard-card" style="width: 18rem;">
                  <%= image_tag "#{journey.city_journeys.first.city.name}.jpg", :class => "dashboard-image" %>
                  <div class="card-body text-center">
                    <p><%= link_to "#{journey.name}", journey_path(journey) %></p>
                    <p><%= journey.tag %></p>
                    <div id="dates">
                      <p> From <%= journey.start_date.strftime("%a %d %B") %> to <%= journey.end_date.strftime("%a %d %B") %> </p>
                    </div>
                    <button id="dashboard-button">
                      <%= link_to journey_path(journey), data: { "turbo-method": :delete }, id:"trash-icon" do %>
                        <i class="fa-solid fa-trash"></i>
                      <% end %>
                  </button>
                  </div>
                </div>
              <% end %>
            <% end %>
        </div>
      <% end %>
  <% end %>
</div>

app/views/pages/dashboard_past.html.erb
<div class="db-banner">
  <h1 class="mb-5"> Dashboard </h1>
</div>

<div class="card-deck card-page-container">

  <ul class="nav nav-tabs mt-5">
    <li class="nav-item">
      <a class="nav-link" aria-current="page"> <%= link_to "Future journeys", dashboard_path, class: "nav-link" %> </a>
    </li>
    <li class="nav-item">
      <a class="nav-link"> <%= link_to "Current journey", dashboard_current_path, class: "nav-link" %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link"> <%= link_to "Past journeys", dashboard_past_path, class: "nav-link active" %></a>
    </li>
  </ul>

  <% if @journeys.empty? %>
    <h3 class='mt-5 mb-5'> You don't have any journeys with us. Start filling your dashboard by planning some trips! </h3>
  <% else %>
    <% if @journeys.first.end_date >= Date.today %>
      <h4 class='mt-5 mb-5'> You don't have any past travel with us </h4>
    <% else %>
      <div class="p-3 m-3 cards-container">
          <% @journeys.each do |journey| %>
          <% if journey.end_date < Date.today %>
            <div class="card shadow p-3 bg-white rounded-lg" id="dashboard-card" style="width: 18rem;">
              <%= image_tag "#{journey.city_journeys.first.city.name}.jpg", :class => "dashboard-image" %>
              <div class="card-body text-center">
                <p><%= link_to "#{journey.name}", journey_path(journey) %></p>
                <p><%= "#{journey.tag}" %></p>
                <div id="dates">
                  <p> From <%= journey.start_date.strftime("%a %d %B") %> to <%= journey.end_date.strftime("%a %d %B") %> </p>
                </div>
                <button id="dashboard-button">
                  <%= link_to journey_path(journey), data: { "turbo-method": :delete }, id:"trash-icon" do %>
                    <i class="fa-solid fa-trash"></i>
                  <% end %>
                </button>
              </div>
            </div>
          <% end %>
          <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div id="top" class="home-banner">
<h1 class="mb-5"> A Trip Well Travelled </h1>
</div>

<div class="my-5 featured-title">
  <%= link_to "Create your own dream adventure", new_journey_path, class:"standard-button mt-5", id:"home-button" %>
</div>

<h2 class="mb-5 mt-4 text-center"> What do we do at Trips Selector? </h2>
<div class="home-info-container d-flex align-content-center justify-content-center">
  <div class="home-info-card">
    <div class="home-info-segment">
      <%= image_tag asset_path("t-d.svg"), width: "350", height: "250" %>
      <p class="fs-4 mt-4"> Tired of spending days preparing your next holiday? </p>
    </div>
    <div class="home-info-segment middle-segment-borders">
        <%= image_tag asset_path("m-d.svg"), width: "350", height: "250" %>
        <p class="fs-4 mt-4"> Trips Selector is a tool to generate a trip for you! </p>
    </div>
    <div class="home-info-segment">
      <%= image_tag asset_path("a-d.svg"), width: "350", height: "250" %>
      <p class="fs-4 mt-4"> Just tell us where, and we tell you the rest!</p>
    </div>
  </div>
</div>

<h1 class="featured-title">Featured Trips To Suit Your Style</h1>
<div class="border featured-trips-container">
  <h3 class="mt-5 text-center">Fancy A Swim?</h3>
  <div class="featured-trips-category-container">
    <div class="featured-card">
      <%= image_tag asset_path("Saint-Malo.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
        <%= link_to "Saint-Malo to Nantes", journey_path(@sea_1), class:"text-decoration-none featured-body-title" %>
          <p class="featured-card-text">
            For an amazing week in and around Britany, discovering one of the most well preserved region in France.
          </p>
      </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("La-Rochelle.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
        <%= link_to "La Rochelle to Ars-en-Ré", journey_path(@sea_2), class:"text-decoration-none featured-body-title" %>
        <p class="featured-card-text">
          A seaside weekend wandering the pretiest beaches on the Atlantic coast.
        </p>
      </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("Biarritz.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
        <%= link_to "Biarritz", journey_path(@sea_3), class:"text-decoration-none featured-body-title" %>
        <p class="featured-card-text">
          Tired of California surfing? Try Biarritz for a change.
        </p>
      </div>
    </div>
  </div>
  <h3 class="mt-5 text-center">Get High</h3>
  <div class="featured-trips-category-container">
    <div class="featured-card">
        <%= image_tag asset_path("Aubenas.jpg"), class: "featured-card-img-top" %>
        <div class="featured-card-body">
            <%= link_to "Aubenas to Lyon", journey_path(@mountain_1), class:"text-decoration-none featured-body-title" %>
            <p class="featured-card-text">
                A week in Auvergne, mixing good food in Lyon's bouchons (local restaurants) and some kayaking in France's nicest gorges.
            </p>
        </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("Annecy.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
          <%= link_to "Annecy to Chambéry", journey_path(@mountain_2), class:"text-decoration-none featured-body-title" %>
          <p class="featured-card-text">
              A week-end near the 2 biggest and wildest lakes in France. Skiing is also on the menu !
          </p>
      </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("Grenoble.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
          <%= link_to "Grenoble", journey_path(@mountain_3), class:"text-decoration-none featured-body-title" %>
          <p class="featured-card-text">
              Grenoble is the city to visit if your two passions in life are cheese and skiing.
          </p>
      </div>
    </div>
  </div>
  <h3 class="mt-5 text-center">Big City Life</h3>
  <div class="featured-trips-category-container">
    <div class="featured-card">
      <%= image_tag asset_path("Paris.jpg"), class: "featured-card-img-top d-flex", width: "400", height: "300" %>
      <div class="featured-card-body">
          <%= link_to "Paris to Versailles", journey_path(@major_city_1), class:"text-decoration-none featured-body-title" %>
          <p class="featured-card-text">
            No time but want to be able to say you've been to France? All you need is a weekend to see the Eiffel Tower and Chateau de Versailles and you'll be a local.
          </p>
      </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("Lille.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
          <%= link_to "Lille to Strasbourg", journey_path(@major_city_2), class:"text-decoration-none featured-body-title" %>
          <p class="featured-card-text">
            With the nicest French around, and the best Christmas market in the country, this will change your mind about the French.
          </p>
      </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("Lyon.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
          <%= link_to "Lyon", journey_path(@major_city_3), class:"text-decoration-none featured-body-title" %>
          <p class="featured-card-text">
            Spend a week-end in what used to be France's capital city, back when the French didn't exist.
          </p>
      </div>
    </div>
  </div>
      <h3 class="mt-5 text-center">For The Foodies</h3>
  <div class="featured-trips-category-container">
    <div class="featured-card">
      <%= image_tag asset_path("Toulouse.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
        <%= link_to "Toulouse to Bordeaux", journey_path(@food_1), class:"text-decoration-none featured-body-title" %>
        <p class="featured-card-text">
          Ok, cut the chit chat, take me to the South-east of France to eat duck liver! I'm preparing my winter body.
        </p>
      </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("Marseille.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
        <%= link_to "Marseille to Lyon", journey_path(@food_2), class:"text-decoration-none featured-body-title" %>
        <p class="featured-card-text">
          Seafood and the french gastronomy capital city all in a weekend, this is how you discover the finest cuisine in the world.
        </p>
      </div>
    </div>

    <div class="featured-card">
      <%= image_tag asset_path("Strasbourg.jpg"), class: "featured-card-img-top" %>
      <div class="featured-card-body">
        <%= link_to "Strasbourg", journey_path(@food_3), class:"text-decoration-none featured-body-title" %>
        <p class="featured-card-text">
          Can't decide if you prefer French food or German beer? Strasbourg is the place to combine your two love.
        </p>
      </div>
    </div>
  </div>
</div>

<%# displays count of users, journeys, cities %>
<div id="user-city-trip-banner" class="home-info-container d-flex align-content-center justify-content-center">
  <div class="home-info-card">
    <div class="home-info-segment">
          <%# <%= image_tag asset_path("c-d.svg"), width: "400", height: "300" %>
          <p class="fs-4 mt-4"> Already <strong> <%= CityJourney.count + 256 %> </strong> cities visited </p>
    </div>
    <div class="home-info-segment middle-segment-borders">
        <%# <%= image_tag asset_path("w-d.svg"), width: "400", height: "300" %>
        <p class="fs-4 mt-4"> <strong> <%= Journey.count + 57 %> </strong> trips planned with Trips Selector ! </p>
    </div>
    <div class="home-info-segment">
      <%# <%= image_tag asset_path("p-d.svg"), width: "400", height: "300" %>
      <p class="fs-4 mt-4"> <strong> <%= User.count + 57 %> </strong> users satisfied and travelling!</p>
    </div>
  </div>
</div>


<a href="#top" data-controller="scroll-to" class="back-to-top"><i class="fa fa-chevron-up" aria-hidden="true"></i>
</a>

app/views/pages/profile.html.erb
<%# profile image upload %>
<%# add additional details, bio/favourite destinations etc %>
<div class="container text-center border w-50 mt-5 mb-5">
  <h2 class="pt-3"><%= "#{@user.username.capitalize}" %>'s profile page</h2>
  <div class="ava pt-3">
  <% if current_user.photo.attached? %>
    <%= cl_image_tag @user.photo.key, height: 200, width: 200, crop: :fill, class: "pfp" %>
    <% else %>
    <%= image_tag "https://www.pngall.com/wp-content/uploads/5/Profile-Avatar-PNG-Free-Download.png", height: 300, width: 300, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
  </div>
  <div class="bio pt-5 pb-5 wrap-text">
    <%= @user.bio %>
  </div>
  <div>
    <p class="pb-4">Your favourite destinations are:</p>
    <li><%= @user.favourite %></li>
    <li><%= @user.second %></li>
    <li class="pb-5"><%= @user.third %></li>
  </div>
  <div class="edit mb-5">
   <%= link_to "Edit your profile", "users/edit" %>
  </div>
</div>