config/routes.rb
Rails.application.routes.draw do
  get 'journeys/index'
  get 'journeys/show'
  get 'journeys/new'
  get 'journeys/create'
  get 'journeys/edit'
  get 'journeys/update'
  get 'journeys/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :journeys
  resources :cities, only:[:index, :show]
  resources :bookmarks, only:[:new, :create]

  get "/journeys/generate/new", to: "journeys#generate_new"
  post "/journeys/create/new", to: "journeys#create_new"

  get 'dashboard', to: 'pages#dashboard'
  get 'dashboard/current', to: "pages#dashboard_current"
  get 'dashboard/past', to: "pages#dashboard_past"

  get 'profile', to: 'pages#profile'

  resources :city_journeys, only:[:update]
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  has_many :city_journeys, dependent: :destroy
  has_many :cities, through: :city_journeys
  has_many :bookmarks
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :name, presence: true
  validates :country, presence: true
  validates :tag, presence: true

end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :index, :show, :create, :edit, :update, :destroy ]
  def index
    @journeys = Journey.all
  end

  def show
    @journey = Journey.find(params[:id])
    @cities = @journey.cities
    @city_journeys = @journey.city_journeys.sort_by(&:start_date)

    @markers = @cities.geocoded.map do |city|
      {
        lat: city.latitude,
        lng: city.longitude,
        info_window: render_to_string(partial: "info_window", locals: { city: city})
      }
    end
  end

  def new
    @journey = Journey.new
    if current_user.nil?
      redirect_to "/users/sign_in"
      flash.notice = "You must be signed in to create your Journey"
    end
  end
# duplicate of above? \/
  def generate_new
    @journey = Journey.new
    if current_user.nil?
      redirect_to "/users/sign_in"
      flash.notice = "You must be signed in to create your Journey"
    end
  end

  def create_new
    @journey = Journey.new(name: current_user.journeys.last.name,
                           country: current_user.journeys.last.country,
                           start_date: current_user.journeys.last.start_date,
                           end_date: current_user.journeys.last.end_date,
                           tag: current_user.journeys.last.tag)
    @journey.user_id = current_user.id
    @journey_params = params[:journey]
    @cities = City.where(country: current_user.journeys.last.country)
    @tagged_cities = []
    # below iterates through each citie's tags, and compares with the users requested tag
    @cities.each do |city|
      city_tags_array = city.tags.downcase.split(", ") #takes the tags of the city in the desired country
      city_tags_array.each do |tag|
        if tag == current_user.journeys.last.tag.downcase #compares city tags with journey tag
          @tagged_cities << city
        end
      end
    end

    # before create, check not same city as cities inside list
    journey_length = @journey.end_date - @journey.start_date + 1
    number_of_stops = [journey_length.to_i / 3,1].max
    first_city = @tagged_cities.sample #chooses at random a city in the right country, with the right tag
    if @journey.save # starts big if statement ** #saves the journey. We can now create city journeys
      city_journey_list = []
      first_cj = CityJourney.new(city: first_city,
                                 journey: @journey,
                                 start_date: @journey[:start_date],
                                 end_date: @journey[:start_date] + 3)
      first_cj.save
      city_journey_list << first_cj #adds the first city to the list of cj for this trip
      until city_journey_list.length == number_of_stops
        previous_city_journey = city_journey_list.last
        cj_saved_city_names = []
        city_journey_list.each do |cj|
          cj_saved_city_names << cj.city.name
        end
        next_city_name = nil
        cj_saved_city_names.each do |city_name|
          while next_city_name.nil? || next_city_name == city_name
            next_cities = []
            tagged_next_cities = []
            previous_city_journey.city.next_cities.each do |city|
              next_cities << City.find_by_name(city)
            end
            next_cities.each do |city|
              next_city_tags_array = city.tags.downcase.split(", ") #takes the tags of the city in the next cities list
              next_city_tags_array.each do |tag|
                if tag == current_user.journeys.last.tag.downcase #compares city tags with journey tag
                  tagged_next_cities << city
                end
              end
            end
            next_city_name = tagged_next_cities.sample.name
          end
        end
        next_city = City.find_by_name(next_city_name)
        city_journey = CityJourney.new(city: next_city,
                                       journey: @journey,
                                       start_date: previous_city_journey.end_date,
                                       end_date: previous_city_journey.end_date + 3)
        if city_journey.save
          city_journey_list << city_journey
        else
          # run city generator again
        end
      end
      city_journey_list.last.end_date = @journey.end_date
      city_journey_list.last.save
      current_user.journeys.last(2).first.destroy
      flash.notice = "Journey created"
      redirect_to journey_path(@journey)
    else
      render :new, status: :unprocessable_entity
      flash.notice = "Journey not created"
    end
  end

  def create
    @journey = Journey.new(journey_params)
    @journey.user_id = current_user.id
    @journey_params = params[:journey]
    # if no tag, @journey.tag = [].sample
    if @journey_params[:tag] == "Surprise Me!"
      tags_to_sample = ["Food", "Mountain", "Sea", "Major City"]
      @journey.tag = tags_to_sample.sample
      @journey_params[:tag] = @journey.tag
    end
    @cities = City.where(country: @journey_params[:country])
    @tagged_cities = []
    @cities.each do |city|
      city_tags_array = city.tags.downcase.split(", ") #takes the tags of the city in the desired country
      city_tags_array.each do |tag|
        if tag == @journey_params[:tag].downcase #compares city tags with journey tag
          @tagged_cities << city
        end
      end
    end

    # before create, check not same city as cities inside list
    journey_length = @journey.end_date - @journey.start_date + 1
    number_of_stops = [journey_length.to_i / 3,1].max
    first_city = @tagged_cities.sample #chooses at random a city in the right country, with the right tag
    if @journey.save # starts big if statement ** #saves the journey. We can now create city journeys
      city_journey_list = []
      first_cj = CityJourney.new(city: first_city,
                                 journey: @journey,
                                 start_date: @journey[:start_date],
                                 end_date: @journey[:start_date] + 3)
      first_cj.save
      city_journey_list << first_cj #adds the first city to the list of cj for this trip
      until city_journey_list.length == number_of_stops
        previous_city_journey = city_journey_list.last
        cj_saved_city_names = []
        city_journey_list.each do |cj|
          cj_saved_city_names << cj.city.name
        end
        next_city_name = nil
        cj_saved_city_names.each do |city_name|
          while next_city_name.nil? || next_city_name == city_name
            next_cities = []
            tagged_next_cities = []
            previous_city_journey.city.next_cities.each do |city|
              next_cities << City.find_by_name(city)
            end
            next_cities.each do |city|
              next_city_tags_array = city.tags.downcase.split(", ") #takes the tags of the city in the next cities list
              next_city_tags_array.each do |tag|
                if tag == @journey_params[:tag].downcase #compares city tags with journey tag
                  tagged_next_cities << city
                end
              end
            end
            next_city_name = tagged_next_cities.sample.name
          end
        end
        next_city = City.find_by_name(next_city_name)
        city_journey = CityJourney.new(city: next_city,
                                       journey: @journey,
                                       start_date: previous_city_journey.end_date,
                                       end_date: previous_city_journey.end_date + 3)
        if city_journey.save
          city_journey_list << city_journey
        else
          # run city generator again
        end
      end
      city_journey_list.last.end_date = @journey.end_date
      city_journey_list.last.save
      flash.notice = "Journey created"
      redirect_to journey_path(@journey)
    else
      render :new, status: :unprocessable_entity
      flash.notice = "Journey not created"
    end
  end

  def edit
    @journey = Journey.find(params[:id])
  end

  def update
    @journey = Journey.new(journey_params)
    if @journey.save
      flash.notice = "Journey edited"
    else
      render :edit, status: :unprocessable_entity
      flash.notice = "Journey not edited"
    end
  end

  def destroy
    @journey = Journey.find(params[:id])
    @journey.destroy
    redirect_back(fallback_location: 'something')
    flash.alert = "You have deleted your journey"
  end

  private

  def journey_params
    params.require(:journey).permit(:start_date, :end_date, :tag, :comment, :user_id, :name, :country)
  end
end

app/views/journeys/_city_journey_card.html.erb
<div class="city-journey-card mt-4 mb-5" data-edit-journey-target="card">
  <%= image_tag("#{city_journey.city.name}.jpg", :class => "city-card-picture") %>
  <div class="pb-3 city-journey-info <%= 'd-none' if city_journey.errors.any? %>" data-edit-journey-target="infos">
      <div>
        <div class="d-flex flex-column justify-content-center align-items-left">
          <div class="w-85">
            <h4 class="m-4"> <strong> <%= city_journey.city.name %> </strong> <%= "from #{city_journey.start_date.strftime("%a %d %B")} to #{city_journey.end_date.strftime("%a %d %B")}" %> </h4>
              <% city_journey.city.activities.each do |activity| %>
                <div class="activities m-4">
                  <strong> <%= activity.name %> :</strong> <%= " #{activity.description}" %>
                </div>
              <% end %>
          </div>
        </div>
      </div>
    <button id="edit-card-button" class="btn standard-button show-card-button" aria-label="Edit stop" data-action="click->edit-journey#displayForm" data-index="<%= index %>" >
      <p class="m-0" data-index="<%= index %>">Change This City</p>
    </button>
  </div>
  <%= simple_form_for city_journey,
    html: {
      class: city_journey.errors.any? ? "" : "d-none",
      data: {
        edit_journey_target: "form",
        action: "submit->edit-journey#update",
        index: index,
        controller: 'flatpickr'
      }
    } do |f|
  %>
    <div class="m-3">
      <div class="edit-form">
        <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
      </div>
      <%= f.association :city, collection: City.order("name") %>
      <%= f.submit "Update journey", class: "btn standard-button mt-2", id:"show-card-button" %>
    </div>
  <% end %>
</div>

app/views/journeys/_info_window.html.erb
<h2><%= city.name %></h2>
<p><%= city.region %></p>

app/views/journeys/_mapbox.html.erb
<div style="height: 600px; position: sticky; top: 5rem; box-shadow: 0px 0px 5px darkgrey;"
  data-controller="map"
  data-map-markers-value="<%= markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  class= "mb-5 card-map-aligner mapboxgl-popup">
</div>

app/views/journeys/_show_partial.html.erb
 <div class="city-banner d-flex justify-content-center align-items-center" style="background-image: url('<%= image_path "#{city_journeys.first.city.name}.jpg"%>')">
    <h1> <%= journey.name %> </h1>
    <% if current_user.nil? || current_user.journeys.last.nil? || current_user.journeys.last.id != journey.id %>
          <%= nil %>
        <% else %>
    <%= button_to raw('<a>Boring! Give me another Journey!</a>'), journeys_create_new_path, method: :post , class:"bn5 mt-4 btn"%>
    <% end %>
  </div>

  <div class="page-container">
    <div class= "">
      <h4 class="mt-5" data-edit-journey-target="title">
        <%= "This journey starts on "%><u><%="#{city_journeys.first.start_date.strftime("%a %d %B")}"%></u> in <u><%="#{city_journeys.first.city.name}"%></u><%=" and ends on "%> <u><%="#{city_journeys.last.end_date.strftime("%a %d %B")}"%></u> <%="in"%> <u><%="#{city_journeys.last.city.name}." %></u>
      </h4>
      <div>
        <% city_journeys.each_with_index do |city_journey, index| %>
          <%= render "journeys/city_journey_card", city_journey: city_journey, index: index %>
        <% end %>
      </div>

      <h4 class="ml-2 p-3"> Enjoy your trip! </h4>
    </div>
    <div style="width: 50%" class="mt-0 m-5">
      <div>
        <% if current_user.nil? || current_user.journeys.last.nil? || current_user.journeys.last.id != journey.id %>
          <%= nil %>
        <% else %>
          <div class="refresh-container d-flex justify-content-center align-items-center">
              <%# <%= button_to raw('<a>Boring! Give me another Journey!</a>'), journeys_create_new_path, method: :post , class:"bn5 mt-4 btn"%>
            <%# <div class="box-ref mt-4">
              <%= button_to raw('<h1>Try Again</h1>'), journeys_create_new_path, method: :post , class:"btn btn-ref"%>
            <%# </div> %>
          </div>
        <% end %>
      </div>
      <%= render "journeys/mapbox", markers: markers %>
    </div>

app/views/journeys/edit.html.erb
<h1>Edit your journey </h1>

<%= simple_form_for(@journey) do |f| %>
  <%= f.input :name %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :tag %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/journeys/generate_new.erb
<div class="form-container mb-4">
  <h1 class="mb-4 mt-4"> Let's get on an adventure again </h1>

  <%= simple_form_for @journey, data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :name, input_html:{value: current_user.journeys.last.name} %>
    <%= f.input :country, priority: [ "France" ], collection: [ "Australia", "Brazil", "France", "New Zealand"], selected: current_user.journeys.last.country %>
    <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } }, input_html:{value: current_user.journeys.last.start_date} %>
    <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } }, input_html:{value: current_user.journeys.last.end_date} %>
    <%= f.input :tag, collection: ["Food", "Mountain", "Sea", "Major City"], selected: current_user.journeys.last.tag %>
    <%= f.submit "Let's try again!" %>
  <% end %>
</div>

app/views/journeys/index.html.erb
<h1>Here are all the journeys</h1>


<% @journeys.each do |journey| %>
<ul>
<li> <%= journey.name %> </li>
<li> <%= journey.start_date %> </li>
<li> <%= journey.end_date %> </li>
<li> <%= journey.tag %> </li>
<li> <%= journey.comment %> </li>
<li> <%= link_to "Delete this journey",  %>
</ul>
<% end %>

app/views/journeys/new.html.erb
<div class="form-container mb-4">
<div class="svg-new-left">
  <%= image_tag asset_path("choose-d.svg"), width: "350", height: "250" %>
  <h3 class="mt-2">Simply fill out the form</h3>
</div>
<div class="svg-new-right">
  <%= image_tag asset_path("map-new-d.svg"), width: "350", height: "250" %>
  <h3 class="mt-2">And a journey will appear!</h3>
</div>
<div class="form-img w-100">
  <h1 class="adv-heading">Ready for an Adventure? </h1>
</div>
<%# implement a button, to autoinput surprise me for all, careful to have seeds for everything tho %>
<div class="form-inputs">
  <%= simple_form_for @journey, data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :name, label: "Name Your Journey" %>
    <%= f.input :country, label: "Where to?", priority: [ "France" ], collection: [ "Australia", "Brazil", "France", "New Zealand"] %>
    <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
    <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
    <%= f.input :tag,
            as: :radio_buttons,
            collection_wrapper_tag: 'div',
            label: "What style of holiday are you after?",
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            collection: [["🌮 Food", "Food"],  ["🗻 Mountain", "Mountain"], ["🏖 Sea", "Sea"], ["🏛 Major City", "Major City"], ["🎲 Surprise Me!", "Surprise Me!"]] %>

    <%= f.submit "Let's travel", class:"btn standard-button", id:"submit-button" %>
  <% end %>
</div>
</div>

  <%# <%= f.collection_radio_buttons :tag, [['Surprise Me!'], ['Mountain']], :first, :last, item_label_class: 'material-symbols-outlined' %>

app/views/journeys/show.html.erb
<div data-controller="edit-journey" data-edit-journey-target="show">

    <%= render"show_partial", city_journeys: @city_journeys, journey: @journey, markers: @markers %>

</div>